id: IAB6F6FC6
legacy_id: P000486
ocr_import_info:
  bdrc_scan_id: W1GS45961
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T07:20:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T20:02:29.167019+00:00'
last_modified: 2022-08-31 04:02:59.875757
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS45961
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1GS45961
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཉག་བླ་རང་རིག་རྡོ་རྗེའི་རྣམ་ཐར་དང་མགུར་འབུམ།
  author: ཉག་བླ་རང་རིག་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7681183595598735
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1GS45964:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS45964
      total_pages: 374
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS45964.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7681183595598735
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
